### ISSUE TITLE
Pay back technical debt

### ISSUE THREAD

**Issue by jacg** [next-exp/IC#478]
This is a catalogue of known technical debt that we have accumulated and know that we need to remove. 

Please **edit this comment** to add any other items that you are aware of. We can have discussions in further comments below, but the catalogue should be clearly visible here, at the top.

1. [x] Liquify cities (#465, #435)
2. [x] Revisit sensor masking
3. [x] Generalize IC to run with different detector configurations
4. [x] Complete event model (#426, #433)
5. [ ] Silence warnings and optimize hypothesis tests (#492, #542, ).
6. [x] Git LFS (#535, #210)
7. [x] Dependency version tracking
8. [x] Fix tests failing recurrently (#517, ...)
9. [x] Create symbols module?
10. [ ] Implement Olivia as a liquid city
11. [ ] Build a system to read and write lt/geo correction data from / to the database
12. [ ] Implement an interface to deal with lt/geo corrections (depends on the previous)

**Comment by jacg** [comment]
I think that the list in the description of this PR is essentially the agenda for the next sprint.

**Comment by jacg** [comment]
I understand that structural issues are boring and that you all want to get on with physics, but

+ We are developing new solid cities, and adding new features to existing solid cities
+ We are adding binary files to the repository without Git LFS being available
+ We are forging ahead without any means to track dependency versions

All of this is resulting in a **huge** accumulation of technical debt. Your ability to make any progress on doing physics, and to understand and compare results that you obtained throughout the history of the project **will grind to a halt** unless something is done about this, sooner rather than later.

**Comment by andLaing** [comment]
There are still various missing 'cities' to have the sensor calibration functionality fully formalised. I've been holding off but we really can't wait any longer especially since Carmen and Jonathan are starting to help on the cal side and need jobs.

Decisions from the high heid yins needed.

**Comment by jjgomezcadenas** [comment]
@jacg I agree with your point of view, but please do not ignore mine.

- we do not have the man power (without @gonzaponte, @abotas and @jacg) to catch up on the TD accumulated.

- chamber is in full swing, producing about 1 M events a day, existing man power totally overcommitted. 

- How do you propose that we repay TD? In my opinion this is only possible with dedicated sprints, involving the best programmers in the team (which includes @jacg and @gonzaponte). Right now,  neither of you are available, and we have lost @abotas. 

- Without a plan to repay TD you are preaching the need to follow the light to a choir of blind.

**Comment by jacg** [comment]
> Without a plan to repay TD ...

That's how it goes with technical debt: it becomes increasingly difficult to repay. Which is why you should develop a **very** strong reluctance to acquire it in the first place.

I'm sorry, I have no solution for you. I can only say *I told you so*. We should never have got into this situation in the first place.

Really, it bears repeating: without a plan to repay technical debt, don't take on technical debt. Those words are easy to say, but it takes immense effort and self-control to actually do it. However, without that self-control, expect pain, mysery and a project that grinds to a halt.

Looking on the bright side, I hope that this will lead to another key shift in your visceral understanding of how things have to be done. I remember the days when you paid lip service to the need for automated tests, but, in practice, rather than building extensive automated tests suites for all code you wrote, you thought that having run a few tests by hand in a notebook on your machine was adequate. It took a long period of me *poniendome muy pesado* and bludgeoning you over the head with the need to write *automated* test suites that get executed whenever an IC developer mereley approaches a keyboard, before you finally got it. But get it you did. Well, you've been paying lip service to the need to avoid technical debt, while accumulating lots of it.

Most of us have to learn these things the painful way. Let's hope that there has been enough pain to drive the point home.

(If we can also push adaptation of *con peras* from the realm of lip service into the realm of standard practice, then I can retire from IC with confidence in its future.)

A few more general words of wisdom: You are physicists, and you want to do physics. Physics is the protagonist. Physics is your aim. Physics is what drives you. Physics is interesting. You are not programmers, and programming is an annoying and relatively unimportant, distraction that diverts your precious time from getting on with physics, right? Please, please understand that, in this day and age, there is no physics without programming. Start paying attention to, enjoying and respecting the software development process, and you wil magically find yourselves doing more and better physics more efficiently.

> How do you propose that we repay TD?

The answer to this question should have been known before taking on the TD. Absent the answer, don't take on the TD.

Try getting a monetary loan without a plan for paying it back: you'll only get one from people who would accept your kneecaps as payment. Don't go there.

**Technical Debt drains your resources.** Avoid taking on technical debt. If you do take on technical debt, make it small and brief. Have a plan for its repayment in place beforehand.
